spring.datasource.url: jdbc:postgresql://localhost:5432/books
spring.datasource.username: root
spring.datasource.password: 123

spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.database: postgresql

spring.flyway.baseline-on-migrate: true

spring.jpa.show-sql: true