spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
  flyway:
    baseline-on-migrate: true

jwt-config:
  access-token-validity-millisecond: 300
  signing-key: "ethalon123sign"
  authorities-key: "scopes"